### ISSUE TITLE
每日总结

### ISSUE THREAD

**Issue by mutex73** [mutex73/AlgoSquirrel#4]
2016年6月27日
　　今天主要讲了大O表示法的数学推导，极限在讨论序列复杂度中的应用。解决了FIB迭代复杂度推导的问题，交流分享了数据库源码的链表实现。

**Comment by vashxzx** [comment]
2016年6月28日
        主要讲了最大子序列的四种算法，但是对于递归实现的算法理解还不够深入。

**Comment by mutex73** [comment]
2016年6月29日
三种查找算法书中给出了经典的实现：二分查找、GCD、取幂，代码应该背下来。
对于递归的算法如何求O仍是个问题，记了一个遗留问题，后面解决时要注意数学上怎样推导递归的复杂度的。

**Comment by vashxzx** [comment]
**关于二分法的心得**

> 1.low<=high，不是low<high
```
若有（2,3）low=0，high=1，这里要找3。

则会有mid=0，A[0]<3，low=mid+1=1;
而下一步的while（low<high）已经不满足。
```

>2.low=mid+1，不是low=mid
```
若有（2,3）low=0，high=1，这里要找3。

则会有mid=0，A[0]<3，low=mid=0;
始终会满足while（low<=high），成为死循环。

```

**Comment by mutex73** [comment]
2016年06月30日
　　今天内容主要是单项链表的实现，算法都很基础，既然基础就一定要扎实，单项链表的实现应该抽时间背下来，应该抬笔就能写出来，做到这种熟练度以后面试笔试so easy

**Comment by mutex73** [comment]
@vashxzx 二分法心得：对对昨天没有认真想为什么要<=，找到元素的最后一步就是low==high，如果循环测试low<high那就永远找不到了。

**Comment by mutex73** [comment]
2016年7月1日
　　双向链表的简单介绍，多项式乘法的两种实现（数组、链表）。重点内容基数排序。

**Comment by mutex73** [comment]
2016年7月2日
    主要讨论了链表的游标实现细节

**Comment by mutex73** [comment]
2016年7月3日
　　交流前端框架的设计问题；数据结构中栈的链式实现。

**Comment by vashxzx** [comment]
2016年7月3日
        栈的数组实现，感觉书翻译的容易使人产生歧义。

**Comment by mutex73** [comment]
2016年7月4日
　　栈的数组游标实现方法，游标的使用时注意：每个栈维护自己的游标，共享必然会出问题。

**Comment by mutex73** [comment]
2016年7月5日
　　栈的应用，主要讲了Linux的栈在内存中的形式

**Comment by vashxzx** [comment]
2016年7月6日
　　李彬讲了队列的数组实现方法和出入队列的例程。

**Comment by mutex73** [comment]
2016年7月7日
　　树的基本概念，主要讲了前序遍历和后序遍历的实现。

**Comment by mutex73** [comment]
2016年7月8日
　　二叉树的基本实现，BST的实现

**Comment by mutex73** [comment]
2016年7月10日
　　BST性能分析

**Comment by mutex73** [comment]
2016年7月11日
　　源码解读，内存池机制

**Comment by mutex73** [comment]
2016年7月15日——7月17日
　　志鑫完成了单旋转和双旋转的讲些，连续三天实现了triple kill

**Comment by mutex73** [comment]
2016年7月18日——7月19日
　　伸展树的定义，以及展开的方法（zig-zig展开，zig-zag展开）

**Comment by mutex73** [comment]
2016年7月20日——7月21日
　　树的遍历，以及b-树的定义等

**Comment by mutex73** [comment]
2016年7月22日
　　b-树收尾

**Comment by mutex73** [comment]
2016年7月26日
　　开始讲哈希表

**Comment by vashxzx** [comment]
2016年7月26日
　　开放定址法。定理5.1的证明比较耐人寻味。

**Comment by vashxzx** [comment]
2016年7月26日
　　开放定址法初始化和查询的例程。其中find例程中使用了一个公式。

> F(i)=F(i-1)+2i-1

`举例说明：
当i=4时，F(i)=16，F(i-1)=9,有16-9=(4+3)*(4-3)。
通式即，F(i)-F(i-1)=i^2-(i-1)^2=(i+i-1)(i+1-i)=2i-1
所以有， F(i)=F(i-1)+2i-1`

**Comment by mutex73** [comment]
2016年7月30日
　　开始优先队列，二叉堆的基本性质和实现，关注的主要是实现方法，其中使用的交换元素的方法很巧妙。

**Comment by mutex73** [comment]
2016年8月15日
　　松鼠复活，明天继续讲，二叉堆
